site_name: WTAI
site_url: https://github.com/Adrianthebeloved/WTAI
repo_url: https://github.com/Adrianthebeloved/WTAI
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy
    - content.tabs.link
    - navigation.sections
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.tasklist
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.arithmatex
  - toc:
      permalink: true
extra_javascript:
  - https://unpkg.com/mermaid@10.9.1/dist/mermaid.min.js
  - assets/mermaid-init.js
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Adrianthebeloved/WTAI
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Architecture: architecture.md
