site_name: Workforce Transformation & Analytics • Implementation Planning & Governance
site_url: https://github.com/Adrianthebeloved/WTAI
repo_url: https://github.com/Adrianthebeloved/WTAI
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy
    - content.tabs.link
    - navigation.sections
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
markdown_extensions:
  - admonition
  - codehilite
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.tasklist
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.arithmatex
  - toc:
      permalink: true
extra_javascript:
  - https://unpkg.com/mermaid@10.9.1/dist/mermaid.min.js
  - assets/mermaid-init.js
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Adrianthebeloved/WTAI
nav:
  - Home: index.md
  - Day 4 — Workforce Transformation & Analytics:
      - Overview: day-4.md
      - Why Now?: day4-why-now.md
      - Reference Architectures for Analytics in Operations: day4-reference-architectures.md
      - "AI in Operations: PdM, Optimization, and Agentic Workflows": day4-ai-in-operations.md
      - "The Data Product Operating Model & Data Contracts": day4-data-product-and-contracts.md
      - "Workforce and Culture: Roles, Skills, and Adoption": day4-workforce-and-culture.md
      - "Interactive Workshop: Human-Machine Collaboration Redesign": day4-workshop-human-machine.md
  - Day 5 — Implementation Planning & Governance:
      - Overview: day-5.md
      - Investment Strategy and Portfolio Shaping: day5-investment-portfolio.md
      - "Governance for the AI Era": day5-governance-ai-era.md
      - "Compliance Focus: Nigeria NDPA 2023 and Global Parity": day5-ndpa-compliance.md
      - "Quality, Observability, and Reliability": day5-quality-observability.md
      - "Platform Blueprint and Reference Implementation Plan": day5-platform-blueprint.md
      - "Interactive Workshop: Pilot Plan to Production Path": day5-workshop-pilot-to-production.md
  - Case Studies: case-studies.md
  - Worksheets: worksheets.md
  - Resources: resources.md
  - Glossary: glossary.md
