site_name: WTAI
site_url: https://github.com/Adrianthebeloved/WTAI
repo_url: https://github.com/Adrianthebeloved/WTAI
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy
    - content.tabs.link
    - navigation.sections
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
markdown_extensions:
  - admonition
  - codehilite
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.tasklist
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.arithmatex
  - toc:
      permalink: true
extra_javascript:
  - https://unpkg.com/mermaid@10.9.1/dist/mermaid.min.js
  - assets/mermaid-init.js
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Adrianthebeloved/WTAI
nav:
  - Home: index.md
  - Masterclass:
      - Day 4 — Workforce Transformation & Analytics:
          - Overview: day-4.md
          - Hour 1 — Why Now?: day4-why-now.md
      - Day 5 — Implementation Planning & Governance: day-5.md
  - Case Studies: case-studies.md
  - Worksheets: worksheets.md
  - Resources: resources.md
  - Glossary: glossary.md
